### PR TITLE
CR can now rebuild itself

### PR DESCRIPTION
**Pull request by MarkowEduard**
files and directories renamed to match their contents.
CR.atg and other files belonging to CR changed that CR can rebuild itself.

### CODE REVIEW

**Comment by norayr** [comment]
thank you!

**Comment by MarkowEduard** [comment]
:-)

    On Thursday, July 5, 2018, 11:33:25 PM GMT+2, Norayr Chilingarian <notifications@github.com> wrote:  
 
 
Merged #1.

**Comment by MarkowEduard** [comment]
Thank you for your effort to tell me how to work with GitHub!
    On Thursday, July 5, 2018, 11:33:33 PM GMT+2, Norayr Chilingarian <notifications@github.com> wrote:  
 
 
thank you!

**Comment by MarkowEduard** [comment]
I changed directories and filenames and adjusted the file contents if necessary, e.g. if I had to change the name of a grammar because there was another grammar with the same name but in a file with a different name.
ToDoAdjusting the documentation.Testing the examples one by one and adjusting them if they don't work as expected.It would be great to supply the book by Terry because there are some examples related to that book.The book should be available as PDF for free. I try to locate it.

    On Thursday, July 5, 2018, 11:33:33 PM GMT+2, Norayr Chilingarian <notifications@github.com> wrote:  
 
 
thank you!

**Comment by norayr** [comment]
try this: http://norayr.am/tmp/cocor/

isn't [this](http://norayr.am/tmp/cocor/pdfvers.pdf) the book you are looking for?

**Pull request merged**
